blank_issues_enabled: false
contact_links:
  - name: ğŸš€ Feature Request
    url: https://github.com/fastlane/fastlane/discussions/new?category_id=13617532
    about: Share ideas for new features
  - name: â“ Ask a Question
    url: https://github.com/fastlane/fastlane/discussions/new?category_id=13617531
    about: Ask the community for help
