blank_issues_enabled: false
contact_links:
  - name: Issue: ğŸ› Bug Report
    url: https://github.com/fastlane/fastlane/issues/new?template=BUG_REPORT.md
    about: If something isn't working as expected ğŸ¤”
  - name: Feature Request
    url: https://github.com/fastlane/fastlane/discussions/new
    about: Share ideas for new features
  - name: Ask a Question
    url: https://github.com/fastlane/fastlane/discussions/new
    about: Ask the community for help
