---
name: Release Step 2 - Create GitHub Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      skip_github_packages:
        description: 'Skip pushing to GitHub Packages'
        required: true
        default: false
        type: boolean
      skip_rubygems:
        description: 'Skip pushing to RubyGems'
        required: true
        default: false
        type: boolean

jobs:
  create_github_release:
    runs-on: macos-latest

    permissions:
      packages: write
      contents: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'

    - name: Install fastlane
      run: bundle install

    - name: Run fastlane
      env:
        FASTLANE_RELEASE_API_BEARER: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_GITHUB_USERNAME: 'ibotpeaches'
      run: |
        bundle exec fastlane create_github_release skip_github_packages:${{ github.event.inputs.skip_github_packages }} skip_rubygems:${{ github.event.inputs.skip_rubygems }}

    - name: Save tag for release announcement
      run: echo "$FASTLANE_RELEASE_VERSION" > release_tag.txt

    - uses: actions/upload-artifact@v6
      with:
        name: release_tag
        path: release_tag.txt
        retention-days: 1
